name: 'Webform Demo: Application/Evaluation System'
type: module
description: 'Demonstrates how to use the Webform module to build an application/evaluation system.'
package: 'Webform Demo'
core_version_requirement: ^9.4 || ^10
dependencies:
  - 'drupal:block'
  - 'drupal:views'
  - 'webform:webform'
  - 'webform:webform_node'

# Information added by Drupal.org packaging script on 2023-10-05
version: '6.2.0-beta7'
project: 'webform'
datestamp: 1696543702
